dist: trusty
sudo: false
language: ruby
bundler_args: "--without assets:development:production"
addons:
  postgresql: '9.6'
cache: bundler
before_script: bundle exec rake db:create db:schema:load
script:
- bundle exec rake
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: O2tKwadZrWceYW2Of4m93Q4+XOnlRLuA/2xOZdaYI4gU41+n0t99ilBYrkyez/FYqRxw5JLcLmItPHjJ/wFu6E2sWNhjU4IJ0JB9dEPfni25MzdsgaOCvf9eaIMgQ8l4HrFKVYYOtWq7NCltZDL26QRGRa8ypHzKR5rdP7tNqNT3czcUTFMHFGYd9Yg/jsc9i3f1yw5+p3m12PkClozzbsEXkACQGepTksiDTLTxr3UAWs9leTSa3Hfk3UwRC4omG3D75bEhTUPOnFavE7lkxC5n3f/e1VnFx4drX/I2ZAQGS6tgHiv355KgI40ChMPbtCwR+tTBVQ+VDKgQLJUb8RP+LR7rzXvgxXQmUAbA/DKYDRT5l5AcNzARRI+NsOhz9tSsqzdqv+vnjRMpftSWJe4rNuHvvO4pG3wfcQIzp5SE/StkO/m3S3GfKz6S7gr/9DGraq2dqGLRmfGl0zqBrBWWAgfsDuEOOGapTvfpAEB75N9j1olA3thGrl3JGQm0duALLps2Umxy67NLctBZFujcYSFaWOS5hqoyiUB0lSKh3z/ke3oI4Wf2Z8YcgWq6lwRmBAjQdHegH6eUwHI3L/AdGZEvWhgORUjBd3yz+fyBtMTNyf72osPMJsEbvQxBhg4bY/BtJCI/w2CwL3AeNWHpqjm080PdRkJjjL28qqY=
  app: adoptadrainsf-staging
  on:
    repo: sfbrigade/adopt-a-drain
    branch: master
